import React, { useState } from 'react';
import { ConceptStage } from '../../components/core/ConceptStage';
import { ExplainPanel } from '../../components/core/ExplainPanel';
import { useLanguage } from '../../components/core/LanguageContext';

const poems = [
    {
        id: 'poem1',
        title: 'Poem 1',
        text: 'Two little monkeys,\nJumping on a tree.\nOne fell down,\nAnd bumped his knee.\nAh! Ah! Ah!',
        isModel: false,
    },
    {
        id: 'poem2',
        title: 'Poem 2',
        text: 'Monkeys swing from tree to tree,\nLaughing loud and wild with glee.\nPeeling bananas, having fun,\nPlaying games in the morning sun!',
        isModel: true,
    },
];

export const Slide3_PoemDetection: React.FC = () => {
    const { language } = useLanguage();
    const [selectedId, setSelectedId] = useState<string | null>(null);

    const text = {
        en: {
            prompt: 'Which poem sounds more like a language model?',
            feedbackIdle: 'Pick a poem to see the reveal.',
            feedbackCorrect: 'Correct. Poem 2 was generated by a language model.',
            feedbackWrong: 'Not this time. Poem 2 was generated by a language model.',
            explain: `
- Modern models can produce fluent, rhythmic text.
- If it is hard to tell, the model is already close to human style.
- This motivates a deeper look at how language models evolved.
`,
        },
        zh: {
            prompt: 'Which poem sounds more like a language model?',
            feedbackIdle: 'Pick a poem to see the reveal.',
            feedbackCorrect: 'Correct. Poem 2 was generated by a language model.',
            feedbackWrong: 'Not this time. Poem 2 was generated by a language model.',
            explain: `
- Modern models can produce fluent, rhythmic text.
- If it is hard to tell, the model is already close to human style.
- This motivates a deeper look at how language models evolved.
`,
        },
    };

    const t = text[language];
    const selected = poems.find((poem) => poem.id === selectedId) ?? null;
    const feedback = selected
        ? selected.isModel
            ? t.feedbackCorrect
            : t.feedbackWrong
        : t.feedbackIdle;

    return (
        <div className="flex h-full gap-4 w-full">
            <ConceptStage>
                <div className="flex flex-col w-full h-full p-6">
                    <div className="text-sm text-gray-500 mb-4">{t.prompt}</div>
                    <div className="grid grid-cols-2 gap-4 flex-1">
                        {poems.map((poem) => {
                            const isSelected = poem.id === selectedId;
                            return (
                                <button
                                    key={poem.id}
                                    type="button"
                                    onClick={() => setSelectedId(poem.id)}
                                    className={`text-left rounded-2xl border p-4 shadow-sm transition ${
                                        isSelected
                                            ? poem.isModel
                                                ? 'border-emerald-500 bg-emerald-50'
                                                : 'border-rose-500 bg-rose-50'
                                            : 'border-gray-200 bg-white hover:border-gray-300'
                                    }`}
                                    aria-pressed={isSelected}
                                >
                                    <div className="text-xs font-semibold uppercase tracking-wide text-gray-500 mb-2">
                                        {poem.title}
                                    </div>
                                    <div className="text-sm text-gray-700 whitespace-pre-line leading-relaxed">
                                        {poem.text}
                                    </div>
                                </button>
                            );
                        })}
                    </div>
                    <div className="mt-4 rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-600">
                        <span className="font-semibold text-gray-700">Output:</span> {feedback}
                    </div>
                </div>
            </ConceptStage>
            <ExplainPanel>{t.explain}</ExplainPanel>
        </div>
    );
};
